(channel-news
  (version 0)
  (entry (commit "a0ef8caff6182ffe99ad680a9052cf69b8eafc57")
         (title (en "The @code{postgresql-role-service-type} changes from @code{(sops services databases)} have been upstreamed to Guix mainline (9d216d2ae9f9a4ff2935c23a209499b17dcb13a5).")
                (it "I cambiamenti del @code{postgresql-role-service-type} in @code{(sops services databases)} sono stati inviati a Guix mainline (9d216d2ae9f9a4ff2935c23a209499b17dcb13a5)."))
         (body (en "To migrate your configuration, it should be simply a matter of replacing every instance @code{(sops services databases)} with @code{(gnu services databases).
The only other difference is that the @code{requirement} file of the @{postgresql-role-configuration} record has been renamed to @code{shepherd-requirement}.")
               (it "Per migrare la tua configurazione, dovrebbe bastare sostituire ogni istanza di @code{(sops services databases)} con @code{(gnu services databases).
L'unica altra differenza è che il campo @code{requirement} del record @{postgresql-role-configuration} è stato rinominato in @code{shepherd-requirement}.")))
  (entry (commit "fa43482b956fa9f355454e9e8939e2e2a4c78130")
         (title (en "Move channel to Github.")
                (it "Migrazione a Github."))
         (body (en "This channel is moving over to https://github.com/fishinthecalculator/sops-guix to lower the bar for contributions.")
               (it "Questo channel si trasferisce su https://github.com/fishinthecalculator/sops-guix per semplificare il processo di contribuzione.")))
  (entry (commit "fdffef2b4a177edc24156a51c0489020cae4287a")
         (title (en "Decrypt secrets in a hierarchy of directories.")
                (it "Decrypt secrets in a hierarchy of directorie."))
         (body (en "This is a breaking change. Now secrets are decrypted in a hierarchy of directories instead of a flat list of files in /run/secrets. This means that a file that for example was decrypted to /run/secrets/my-secret-file will now be decrypted to /run/secrets/my/secret/file .")
               (it "Questo è un change che rompe gli script. Ora i secrets sono decrittati in una gerarchia di cartelle dentro /run/secrets. Questo significa che un file che per esempio era decrittato in /run/secrets/my-secret-file ora sarà decrittato in /run/secrets/my/secret/file .")))
  (entry (commit "cde6fba1d35139156c20cb2d45987b1005e7ac51")
         (title (en "Add Guix Home service.")
                (it "Aggiunto servizio Guix Home."))
         (body (en "A new userspace home-sops-secrets-service-type is added in the (sops home services sops) module, with some limitations with regard to the system one. Most notable ones are: it makes no sense to generate a GPG key so the option is not available and secrets are automatically decrypted to /run/user/$UID/secrets which is usually mounted on tmpfs.")
               (it "Viene aggiunto un nuovo home-sops-secrets-service nel modulo (sops home services sops), con alcune limitazioni rispetto al servizio di sistema. Quelle degne di nota sono: non ha più senso generare la chiave GPG quindi l'opzione è stata rimossa e i secrets vengono automaticamente decrittati in /run/user/$UID/secrets che solitamente è montato su tmpfs.")))
  (entry (commit "d852182ac50639641bc2b8aa542c11215eb3ef01")
         (title (en "Make decryption happen from a Shepherd service inside a ramfs file-system.")
                (it "I secrets vengono decrittati da un servizio Shepherd in un file system ramfs."))
         (body (en "Clear text secrets now never hit the disk. A ramfs filesystem is mounted at the configured secrets directory, and the activation happens inside a one shot Shepherd services. This means that from now on Shepherd services requiring secrets must require the sops-secrets service. To transition from the old activation method first reconfigure your system, delete the contents of your secrets directory (usually /run/secrets), and reboot your system.")
               (it "I secret in chiaro ora non finiscono mai su disco. Viene montato un file system ramfs alla posizione configurata come secrets-directorty e l'attivazione avviene in un servizio Shepherd. Questo implica che ora i servizi Shepherd che necessitano di secrets devono richiedere la dipendenza sops-secret. Per migrare dal vecchio metodo di attivazione prima di tutto riconfigura il tuo sistema, cancella il contenuto della cartella secrets-directory e riavvia il sistema.")))
  (entry (commit "c16373f4c1c6e414b5645ad269fa6c26b64559de")
         (title (en "Move sops-secret record to (sops secrets).")
                (it "Il record sops-secret è stato spostato nel modulo (sops secrets)."))
         (body (en "The sops-secret record has been moved over to (sops secrets), hence this module must be imported everywhere some sops-secret related procedure has been used. Apologies for breaking configurations but this helped in a refactor to introduce a Guix Home service for SOPS secrets.")
               (it "Il record sops-secret è stato spostato nel modulo (sops secrets), quindi il modulo va importato ovunque venga usata qualche procedura legata a sops-secret. Mi scuso per aver rotto le configurazioni ma è stato funzionale ad un refactor che abilita la possibilità di introdurre un servizio Guix Home per i SOPS secrets."))))
